### ISSUE TITLE
Reproducibility Check 2

### ISSUE THREAD

**Issue by HongYongGi** [simonsf/RTP-Net#2]
Hello, I'm trying to run the training code, but I'm running into a lot of problems. Is there any modified code? I want to reproduce your experiment results.

It would be appreciated if you could explain a bit more about the experimental procedure.

have a good day.

**Comment by HongYongGi** [comment]
If possible, please upload the csv file as an example.

**Comment by HongYongGi** [comment]
Hello. I'm impressive to read your paper. So I'm trying to your paper experiment. But, This Code is not working. 

I want to reproduce your experiment results.

It would be appreciated if you could explain a bit more about the experimental procedure or Code update, Plz. 

Have a nice day~ :)

**Comment by simonsf** [comment]
The csf file is now uploaded as requested. Please check the latest v1.1. Thanks.
